### ISSUE TITLE
ENOENT when installing

### ISSUE THREAD

**Issue by TheRealGangstaCoder** [exponentjs/instapromise#1]
C:>npm install instapromise -g
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "ins
tall" "instapromise" "-g"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! path C:\Users\user\AppData\Roaming\npm\node_modules.staging\instapromise-fe12fb3c\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\user\AppData\Roaming\npm\node_modules.staging\ins
tapromise-fe12fb3c\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\user\AppData\Roaming\npm\node_modules.staging\ins
tapromise-fe12fb3c\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

from npm-debug.log
19 http request GET https://registry.npmjs.org/instapromise
20 info retry will retry, error on last attempt: Error: unexpected end of file

**Comment by ide** [comment]
It looks like there's some bug with your npm configuration. Instapromise is installing fine on macOS and the CI systems (Ubuntu). I don't think we'll be able to help you with this. If you dig deeper and find the root cause and see that it's a problem with Instapromise, feel free to open another issue.

**Comment by TheRealGangstaCoder** [comment]
Did some more troubleshooting and noticed that the published tarball is missing the package.json file

C:>npm view instapromise dist.tarball
https://registry.npmjs.org/instapromise/-/instapromise-2.0.4.tgz

Downloaded and opened with 7zip, and package.json missing.

I manually added it and installed locally, and that worked

**Comment by ide** [comment]
Thanks for investigating. That's so weird. I published 2.0.5 and verified that package.json is in the tarball, can you give that a try?

**Comment by TheRealGangstaCoder** [comment]
2.0.5 worked perfectly!
